---
coverage:
  precision: 0 # xx%
  round: down # round down
  range: 39..75 # red -> yellow (this range) -> green

  status:
    project:
      default:
        against: auto # auto compares coverage to the previous base commit
        target: auto # automatically calculate coverage target - should increase
        threshold: 2% # allow for 2% reduction without failing
    patch:
      default:
        against: parent
        target: auto
    changes: false

ignore:
  - "vendor"
  - "ipxe/"
