// Code generated by "stringer -type=facility -output=facility_string.go"; DO NOT EDIT.

package syslog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[kern-0]
	_ = x[user-1]
	_ = x[mail-2]
	_ = x[daemon-3]
	_ = x[auth-4]
	_ = x[syslog-5]
	_ = x[lpr-6]
	_ = x[news-7]
	_ = x[uucp-8]
	_ = x[clock-9]
	_ = x[authpriv-10]
	_ = x[ftp-11]
	_ = x[ntp-12]
	_ = x[audit-13]
	_ = x[alert-14]
	_ = x[cron-15]
	_ = x[local0-16]
	_ = x[local1-17]
	_ = x[local2-18]
	_ = x[local3-19]
	_ = x[local4-20]
	_ = x[local5-21]
	_ = x[local6-22]
	_ = x[local7-23]
}

const _facility_name = "kernusermaildaemonauthsysloglprnewsuucpclockauthprivftpntpauditalertcronlocal0local1local2local3local4local5local6local7"

var _facility_index = [...]uint8{0, 4, 8, 12, 18, 22, 28, 31, 35, 39, 44, 52, 55, 58, 63, 68, 72, 78, 84, 90, 96, 102, 108, 114, 120}

func (i facility) String() string {
	if i >= facility(len(_facility_index)-1) {
		return "facility(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _facility_name[_facility_index[i]:_facility_index[i+1]]
}
