// Code generated by "stringer -type=severity -output=severity_string.go"; DO NOT EDIT.

package syslog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EMERG-0]
	_ = x[ALERT-1]
	_ = x[CRIT-2]
	_ = x[ERR-3]
	_ = x[WARNING-4]
	_ = x[NOTICE-5]
	_ = x[INFO-6]
	_ = x[DEBUG-7]
}

const _severity_name = "EMERGALERTCRITERRWARNINGNOTICEINFODEBUG"

var _severity_index = [...]uint8{0, 5, 10, 14, 17, 24, 30, 34, 39}

func (i severity) String() string {
	if i >= severity(len(_severity_index)-1) {
		return "severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _severity_name[_severity_index[i]:_severity_index[i+1]]
}
